import { describe, it, expect } from 'vitest';
import { blankPlan, policySchema, flowSchema, eventSchema, debtSchema, fixedDate, fingerprint, type PlannerPlan, type Snapshot, type Position } from './model';
import { simulate, baseScenario, selectYears, eventDate, resolveDate } from './engine';
describe('연결 연금의 실제 출금 원천', () => {
    const linked = () => {
        const p=plan(); p.endDate='2026-03-31';
        const contract=pos('contract',0,'pension'); contract.source.type='PENSION'; contract.source.detail={linkedStockId:'account',expectedMonthlyPayout:150} as any;
        const a=pos('a',100,'investment'),b=pos('b',100,'investment');
        for(const item of [a,b]){item.source.type='STOCK';item.source.detail={accountName:'account'} as any;}
        p.flows=[flow('payout','withdrawal',150,{assetId:'contract',amountSource:'assetPension',withdrawalAssetIds:['a','b'],withdrawalAccountAssetId:'a',withholding:10})];
        return {p,positions:[pos('cash',0),contract,a,b]};
    };
    it('등록 지급액과 출금 목록을 분리하고 합산 잔액 소진 후에만 미충족을 한 번 기록한다',()=>{
        const {p,positions}=linked(),r=simulate(snap(p,positions));
        expect(r.status).not.toBe('invalid');
        expect(r.months.map(m=>m.withdrawals)).toEqual([150,50,0]);
        expect(r.months.map(m=>m.shortfall)).toEqual([0,100,150]);
        expect(r.months.map(m=>m.taxes)).toEqual([15,5,0]);
        expect(r.months[2].closingCash).toBe(180);
        expect(r.months[2].balances.contract).toBe(0);
        expect(r.firstShortfall).toBe('2026-02');
        expect(r.months[0].entries.filter(e=>e.kind==='withdrawal').map(e=>e.assetId)).toEqual(['a','b']);
    });
    it('누락·중복·빈 출금 목록 및 예전 0원 연금 직접 인출을 차단한다',()=>{
        for(const ids of [undefined,[],['a','a'],['missing']]){
            const {p,positions}=linked();p.flows[0].withdrawalAssetIds=ids;
            expect(simulate(snap(p,positions)).status).toBe('invalid');
        }
    });
    it('계좌명이 바뀌어도 자산 ID 목록은 유지하고 구성 변경은 재확인을 요구한다',()=>{
        const {p,positions}=linked();
        for(const item of positions.filter(x=>x.source.type==='STOCK'))(item.source.detail as any).accountName='renamed';
        expect(simulate(snap(p,positions)).status).not.toBe('invalid');
        const extra=pos('c',100,'investment');extra.source.type='STOCK';extra.source.detail={accountName:'renamed'} as any;
        expect(simulate(snap(p,[...positions,extra])).issues.some(i=>i.code==='ACCOUNT_MEMBERSHIP')).toBe(true);
    });
});
function plan(): PlannerPlan { return { ...blankPlan('2025-12-31'), endDate: '2026-12-31', inflation: 0, coverage: { assets: 'provided', income: 'confirmedNone', expenses: 'confirmedNone', taxes: 'confirmedNone', insurance: 'confirmedNone' } }; }
function pos(id: string, balance: number, role = 'cash', extra = {}) { return { ...policySchema.parse({ assetId: id, role, confirmed: true, annualGrowth: 0, dividendYield: 0, dividendWithholding: 0, withdrawalWithholding:0, ...extra }), name: id, balance, source: { id, name: id, type: role === 'property' ? 'REAL_ESTATE' : 'SAVINGS', detail: {} } } as Position; }
function snap(p: PlannerPlan, positions: Position[]): Snapshot {
    p=structuredClone(p);
    for(const [key,kinds] of Object.entries({income:['income','pension','rent'],expenses:['expense'],taxes:['tax'],insurance:['insurance']}))if((p.coverage as any)[key]==='confirmedNone'&&p.flows.some(f=>kinds.includes(f.kind)&&(f.amount??0)>0))(p.coverage as any)[key]='provided';
    return { id: fingerprint({ p, positions }), assetRevision: 'fixture', capturedAt: '2026-01-01', plan: p, positions, debts: p.debts, issues: [] }; }
function flow(id: string, kind: string, amount: number, extra = {}) { return flowSchema.parse({ id, name: id, kind, amount, start: fixedDate('2026-01-01'), frequency: 'monthly', confirmed: true, withholding: 0, ...extra }); }
function event(id: string, kind: string, date: string, amount: number | null, extra = {}) { return eventSchema.parse({ id, name: id, kind, amount, at: fixedDate(date), ...extra }); }
describe('통합 월별 원장 기준 사례', () => {
    it('준공 뒤 세금만 있으면 준공 전 기간을 0원으로 확정하지 않는다',()=>{const p=plan();p.coverage.taxes='provided';p.flows=[flow('tax','tax',100,{assetId:'house',scope:'holding',basis:'estimate',start:fixedDate('2026-07-01')})];const r=simulate(snap(p,[pos('house',1000,'property',{propertyState:'construction'})]));expect(r.status).toBe('partial');expect(r.issues.some(i=>i.code==='PROPERTY_TAX_GAP')).toBe(true)})
    it('세금 적용기간과 납부월을 분리한다',()=>{const p=plan();p.flows=[flow('tax','tax',100,{assetId:'house',scope:'holding',basis:'estimate',frequency:'annual',paymentMonth:9,start:fixedDate('2026-01-01')})];const r=simulate(snap(p,[pos('cash',1000),pos('house',1000,'property',{propertyState:'construction'})]));expect(r.status).toBe('complete');expect(r.months[0].taxes).toBe(0);expect(r.months[8].taxes).toBe(100)})
    it('계좌 고갈 시 원천세도 목표액이 아닌 실제 인출액에만 적용한다',()=>{const p=plan();p.flows=[flow('irp','withdrawal',300,{assetId:'irp',withholding:10})];const r=simulate(snap(p,[pos('irp',100,'pension')]));expect(r.months[0].withdrawals).toBe(100);expect(r.months[0].taxes).toBe(10);expect(r.months[0].closingCash).toBe(90);expect(r.months[1].taxes).toBe(0)})
    it('생활비 자동 충당은 원천세를 뺀 순액을 기준으로 인출한다',()=>{const p=plan();p.flows=[flow('living','expense',90)];const r=simulate(snap(p,[pos('irp',100,'pension',{allowWithdrawal:true,withdrawalWithholding:10})]));expect(r.months[0].withdrawals).toBe(100);expect(r.months[0].spending).toBe(90);expect(r.months[0].taxes).toBe(10);expect(r.months[0].shortfall).toBe(0)})
    it('없음 확인과 양수 생활비가 충돌하면 입력 오류로 중단한다',()=>{const p=plan();p.flows=[flow('living','expense',100)];const s=snap(p,[pos('cash',100)]);s.plan.coverage.expenses='confirmedNone';expect(simulate(s).status).toBe('invalid')})
    it('원본 자산의 등록 지급액을 연결하면 저장 스냅샷의 해당 금액을 사용한다', () => { const p = plan(); p.flows = [flow('national', 'pension', 999, { assetId: 'national', amountSource: 'assetPension' })]; const asset = pos('national', 0, 'entitlement'); asset.source = { ...asset.source, type: 'PENSION', detail: { expectedMonthlyPayout: 1000 } } as any; const r = simulate(snap(p, [asset])); expect(r.months[0].income).toBe(1000); asset.source = { ...asset.source, detail: { expectedMonthlyPayout: 1200 } } as any; expect(simulate(snap(p, [asset])).months[0].income).toBe(1200); });
    it('동일 연금 수급권에 연결한 외부 지급 중복은 거부한다', () => { const p = plan(); p.flows = [flow('one', 'pension', 100, { assetId: 'national' }), flow('two', 'pension', 100, { assetId: 'national' })]; expect(simulate(snap(p, [pos('national', 0, 'entitlement')])).status).toBe('invalid'); });
    it('6월 말 유입된 투자 원금은 6월 이전 수익을 만들지 않는다', () => { const p = plan(); p.events = [event('money', 'inflow', '2026-06-30', 1e6), event('invest', 'transfer', '2026-06-30', 1e6, { targetId: 'invest' })]; const r = simulate(snap(p, [pos('cash', 0), pos('invest', 0, 'investment', { annualGrowth: 12, dividendYield: 12 })])); expect(r.months[4].balances.invest).toBe(0); expect(r.months[5].balances.invest).toBe(1e6); expect(r.months[5].income).toBe(1e6); expect(r.months[6].balances.invest).toBeGreaterThan(1e6); });
    it('늦게 유입한 현금은 과거 미충당 비용을 갚고 가짜 여유 현금을 만들지 않는다', () => { const p = plan(); p.flows = [flow('bill', 'expense', 100, { frequency: 'once', start: fixedDate('2026-01-15') })]; p.events = [event('money', 'inflow', '2026-02-15', 200)]; const r = simulate(snap(p, [pos('cash', 0)])); expect(r.months[0].unpaid).toBe(100); expect(r.months[1].unpaid).toBe(0); expect(r.months[1].closingCash).toBe(100); expect(r.months[1].spending).toBe(100); });
    it('같은 날 정기 수입으로 일회성 비용을 지급할 수 있다', () => { const p = plan(); p.flows = [flow('salary', 'income', 100)]; p.events = [event('bill', 'expense', '2026-01-31', 100)]; const r = simulate(snap(p, [pos('cash', 0)])); expect(r.months[0].shortfall).toBe(0); expect(r.months[0].closingCash).toBe(0); });
    it('사용승인 전날까지의 기간은 사용승인 이동과 함께 이동한다', () => { const events = [event('approval', 'approval', '2026-06-01', null, { assetId: 'home' })]; expect(resolveDate({ ...fixedDate(''), anchorId: 'approval', offsetDays: -1 }, events)).toBe('2026-05-31'); expect(resolveDate({ ...fixedDate(''), anchorId: 'approval', offsetDays: -1 }, events, { ...baseScenario, eventShifts: { approval: 1 } })).toBe('2026-06-30'); });
    it('G01: 1200만원 현금 + 월100만원 연금 - 120만원 생활비 = 960만원', () => { const p = plan(); p.flows = [flow('pension', 'pension', 1e6), flow('living', 'expense', 1.2e6)]; const r = simulate(snap(p, [pos('cash', 12e6)])); expect(r.status).toBe('complete'); expect(r.months[11].closingCash).toBe(9.6e6); expect(selectYears(r)[0].income).toBe(12e6); });
    it('G02: 6월 보증금/예치금 회수는 소득이 아닌 자산 이동', () => { const p = plan(); p.events = [event('maturity', 'depositRecovered', '2026-06-15', 10e6, { assetId: 'deposit' })]; const r = simulate(snap(p, [pos('cash', 0), pos('deposit', 10e6, 'deposit')])); expect(r.months[4].closingCash).toBe(0); expect(r.months[5].closingCash).toBe(10e6); expect(r.months[5].income).toBe(0); expect(r.months[5].netWorth).toBe(10e6); });
    it('G03: 잔액100만원에서 생활비30만원을 충당하면 4월10만원만 지급', () => { const p = plan(); p.flows = [flow('living', 'expense', 300000)]; const r = simulate(snap(p, [pos('invest', 1e6, 'investment', { allowWithdrawal: true })])); expect(r.firstShortfall).toBe('2026-04'); expect(r.months[3].withdrawals).toBe(100000); expect(r.months[3].shortfall).toBe(200000); expect(r.months[3].balances.invest).toBe(0); expect(r.months[3].recurringNet).toBe(-300000); });
    it('G04: 보유 주택5억-대출1억+현금1천만=4.1억, 임대/재건축 없음', () => { const p = plan(); p.debts = [debtSchema.parse({ id: 'loan', name: '대출', kind: 'loan', balance: 1e8, interestRate: 0, repayment: 'interestOnly', maturity: fixedDate('2030-01-01') })]; const r = simulate(snap(p, [pos('cash', 1e7), pos('home', 5e8, 'property')])); expect(r.months[0].netWorth).toBe(4.1e8); expect(r.resolvedEvents).toEqual([]); });
    it('G05: 받은 보증금은 현금과 부채에 동시에 반영하고 반환', () => { const p = plan(); p.debts = [debtSchema.parse({ id: 'tenant', name: '보증금', kind: 'deposit', balance: 0, repayment: 'interestOnly', maturity: fixedDate('2026-12-15') })]; p.events = [event('receive', 'depositReceived', '2026-01-05', 2e7, { targetId: 'tenant' })]; const r = simulate(snap(p, [pos('cash', 0)])); expect(r.months[0].closingCash).toBe(2e7); expect(r.months[0].netWorth).toBe(0); expect(r.months[11].closingCash).toBe(0); expect(r.months[11].debts.tenant).toBe(0); expect(r.months[11].entries.find(e => e.kind === 'principal')?.date).toBe('2026-12-15'); });
    it('G06: 미입력은 계산상 0이어도 안전으로 확정하지 않음', () => { const p = plan(); p.coverage = blankPlan().coverage; const r = simulate(snap(p, [])); expect(r.status).toBe('partial'); expect(r.issues.some(i => i.code === 'COVERAGE_expenses')).toBe(true); });
    it('출금 목표와 실제 인출을 분리하고 잔액은 음수가 되지 않음', () => { const p = plan(); p.flows = [flow('withdraw', 'withdrawal', 300000, { assetId: 'irp' })]; const r = simulate(snap(p, [pos('irp', 1e6, 'pension')])); expect(r.months[3].entries[0].requested).toBe(300000); expect(r.months[3].entries[0].paid).toBe(100000); expect(r.months[3].unpaid).toBe(0); expect(r.months[4].withdrawals).toBe(0); });
    it('원금 미상환은 잔여 부채로만 남고 새 부채로 이중 차감하지 않음', () => { const p = plan(); p.debts = [debtSchema.parse({ id: 'loan', name: '대출', kind: 'loan', balance: 100, interestRate: 0, repayment: 'interestOnly', maturity: fixedDate('2026-02-10') })]; const r = simulate(snap(p, [pos('cash', 0)])); expect(r.months[1].netWorth).toBe(-100); expect(r.months[1].unpaid).toBe(0); expect(r.months[2].shortfall).toBe(0); });
    it('현금→현금 이체는 소득·총현금·순자산을 늘리지 않음', () => { const p = plan(); p.flows = [flow('transfer', 'transfer', 10, { assetId: 'a', targetId: 'b', frequency: 'once', start: fixedDate('2026-01-15') })]; const r = simulate(snap(p, [pos('a', 100), pos('b', 0)])); expect(r.status).toBe('complete'); expect(r.months[0].closingCash).toBe(100); expect(r.months[0].netWorth).toBe(100); });
    it('투자→투자 이전은 같은 자산 이동이며 소득 아님', () => { const p = plan(); p.flows = [flow('transfer', 'transfer', 50, { assetId: 'a', targetId: 'b', frequency: 'once', start: fixedDate('2026-01-15') })]; const r = simulate(snap(p, [pos('a', 100, 'investment'), pos('b', 0, 'investment')])); expect(r.months[0].netWorth).toBe(100); expect(r.months[0].entries[0].assetDelta).toBe(0); });
    it('준공 지연은 연결된 임대 시작만 이동하고 고정 분담금은 유지', () => { const p = plan(); p.events = [event('complete', 'completion', '2026-03-31', null, { assetId: 'home' }), event('cost', 'expense', '2026-02-10', 100)]; p.flows = [flow('rent', 'rent', 10, { assetId: 'home', start: { ...fixedDate(''), anchorId: 'complete', offsetMonths: 1 } })]; const s = snap(p, [pos('home', 1000, 'property'), pos('cash', 1000)]), before = JSON.stringify(s); const r = simulate(s, { ...baseScenario, id: 'delay', eventShifts: { complete: 3 } }); expect(r.resolvedEvents.find(e => e.id === 'complete')?.date).toBe('2026-06-30'); expect(r.resolvedEvents.find(e => e.id === 'cost')?.date).toBe('2026-02-10'); expect(r.months[5].income).toBe(0); expect(r.months[6].income).toBe(10); expect(JSON.stringify(s)).toBe(before); });
    it('연도만 입력한 일정은 가정 월이 없으면 미확정', () => { const e = event('x', 'inflow', '', 100, { at: { value: '2027', precision: 'year', offsetMonths: 0 } }); expect(eventDate(e, [e], baseScenario)).toBeNull(); expect(resolveDate({ ...e.at, assumedMonth: 2 }, [])).toBe('2027-02-28'); });
    it('일정 순환 연결을 차단', () => { const p = plan(); p.events = [event('a', 'inflow', '', 1, { at: { ...fixedDate(''), anchorId: 'b' } }), event('b', 'inflow', '', 1, { at: { ...fixedDate(''), anchorId: 'a' } })]; expect(simulate(snap(p, [pos('cash', 0)])).status).toBe('invalid'); });
    it('동일 세목·범위의 기간 중첩은 차단', () => { const p = plan(); p.flows = [flow('a', 'tax', 10, { scope: 'home-tax', basis: 'estimate' }), flow('b', 'tax', 10, { scope: 'home-tax', basis: 'estimate' })]; expect(simulate(snap(p, [pos('cash', 1000)])).issues.some(i => i.code === 'TAX_OVERLAP')).toBe(true); });
    it('시가 변경은 현금 유입이 아님, 매각 후 임대 수입 중단', () => { const p = plan(); p.events = [event('v', 'valuation', '2026-02-01', 2000, { assetId: 'home' }), event('sell', 'sale', '2026-03-01', 2100, { assetId: 'home' })]; p.flows = [flow('rent', 'rent', 10, { assetId: 'home' })]; const r = simulate(snap(p, [pos('cash', 0), pos('home', 1000, 'property')])); expect(r.months[1].income).toBe(10); expect(r.months[1].balances.home).toBe(2000); expect(r.months[2].income).toBe(0); expect(r.months[2].balances.home).toBe(0); });
    it('원천세는 한 번 납부하고 연간 정산에서 기납부액을 공제', () => { const p = plan(); p.endDate = '2027-06-30'; p.flows = [flow('income', 'income', 1000, { withholding: 10, end: fixedDate('2026-12-31') })]; p.events = [event('settle', 'taxSettlement', '2027-05-10', 1000, { taxYear: 2026, basis: 'confirmed estimate', creditSourceIds: ['income'] })]; const r = simulate(snap(p, [pos('cash', 0)])); expect(selectYears(r)[0].taxes).toBe(1200); expect(r.months[16].taxes).toBe(-200); expect(r.months[16].closingCash).toBe(11000); });
    it('시나리오 ID가 같아도 가정이 다르면 다른 실행 ID', () => { const s = snap(plan(), [pos('cash', 100)]); expect(simulate(s).id).not.toBe(simulate(s, { ...baseScenario, expensePercent: 1 }).id); });
});
