import {useMemo,useState,type ReactNode} from 'react'
import type {IncomeTaxSettings,PensionSimPlan,PensionSource,PensionSourceTaxSettings} from '@/types'

type QuestionKind='funding'|'retirementPrincipal'|'exemptPrincipal'|'splitInvalid'|'retirementTaxRate'|'firstReceiptYear'|'lifetime'
export interface IrpFundingQuestion {key:string;source:PensionSource;kind:QuestionKind}

export function irpFundingQuestions(plan:PensionSimPlan,value:IncomeTaxSettings):IrpFundingQuestion[]{
  return plan.sources.filter(s=>s.taxType==='irp').flatMap(source=>{
    const p=value.sources?.[source.id]??{},out:IrpFundingQuestion[]=[]
    const add=(kind:QuestionKind)=>out.push({key:`${source.id}:${kind}`,source,kind})
    if(!p.fundingKind){add('funding');return out}
    if(p.fundingKind==='mixed'){
      if(p.retirementPrincipal==null)add('retirementPrincipal')
      if(p.exemptPrincipal==null)add('exemptPrincipal')
      if(p.retirementPrincipal!=null&&p.exemptPrincipal!=null&&p.retirementPrincipal+p.exemptPrincipal>source.principal){add('splitInvalid');return out}
    }
    const retirement=p.fundingKind==='retirement'?source.principal:p.fundingKind==='mixed'?(p.retirementPrincipal??0):0
    const personal=p.fundingKind==='personal'||(p.fundingKind==='mixed'&&p.retirementPrincipal!=null&&p.exemptPrincipal!=null&&p.retirementPrincipal+p.exemptPrincipal<=source.principal&&source.principal-p.retirementPrincipal-p.exemptPrincipal>0)
    if(retirement>0){
      if(p.retirementTaxRate==null)add('retirementTaxRate')
      if(p.firstReceiptYear==null)add('firstReceiptYear')
    }
    if(personal&&p.lifetime==null)add('lifetime')
    return out
  })
}

const won=(n:number)=>`${Math.round(n).toLocaleString('ko-KR')}원`
const button='rounded-lg border border-gray-600 bg-gray-800 px-3 py-2 text-left text-xs hover:border-blue-400 hover:bg-gray-700'
const input='w-full rounded border border-gray-600 bg-gray-950 p-2 text-sm text-gray-100'

export function IrpFundingInterview({plan,value,onChange,onSave,dirty,saving}:{plan:PensionSimPlan;value:IncomeTaxSettings;onChange:(s:IncomeTaxSettings)=>void;onSave?:()=>void;dirty?:boolean;saving?:boolean}){
  const [skipped,setSkipped]=useState<Set<string>>(()=>new Set())
  const [draft,setDraft]=useState<Record<string,string>>({})
  const questions=useMemo(()=>irpFundingQuestions(plan,value),[plan,value])
  const current=questions.find(q=>!skipped.has(q.key))
  const patch=(sourceId:string,valuePatch:Partial<PensionSourceTaxSettings>)=>{
    onChange({...value,sources:{...value.sources,[sourceId]:{...value.sources?.[sourceId],...valuePatch}}})
  }
  const draftValue=(key:string,fallback='')=>draft[key]??fallback
  const set=(key:string,v:string)=>setDraft(d=>({...d,[key]:v}))
  const number=(key:string)=>{const v=draft[key];return v==null||v.trim()===''?undefined:Number(v)}
  const skip=()=>current&&setSkipped(old=>new Set([...old,current.key]))
  const card=(children:ReactNode)=><div className="mt-3 space-y-3 rounded-lg border border-blue-500/40 bg-gray-950/70 p-4">{children}</div>
  return <section className="my-3 rounded-xl border border-blue-500/40 bg-blue-950/20 p-3" data-irp-interview>
    <div className="flex flex-wrap items-start justify-between gap-2"><div><h4 className="text-sm font-semibold text-blue-200">빈칸 문답으로 채우기</h4><p className="mt-1 text-xs text-gray-400">계좌별로 계산에 필요한 질문만 하나씩 보여줍니다. 답을 모르면 확인 위치를 읽고 건너뛸 수 있습니다.</p></div><span className="rounded-full bg-gray-800 px-2 py-1 text-xs">남은 질문 {questions.length}개</span></div>
    {!current&&card(<><p className="text-sm font-semibold text-emerald-300">현재 확인 가능한 IRP 질문을 모두 처리했습니다.</p>{skipped.size>0&&<p className="text-xs text-amber-200">이번에 건너뛴 질문 {skipped.size}개는 값이 저장되지 않았습니다. 아래 버튼으로 다시 확인할 수 있습니다.</p>}<div className="flex flex-wrap gap-2">{skipped.size>0&&<button type="button" className={button} onClick={()=>setSkipped(new Set())}>건너뛴 질문 다시 보기</button>}{dirty&&onSave&&<button type="button" className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-semibold text-white" disabled={saving} onClick={onSave}>{saving?'저장 중…':'답변을 실제 데이터에 저장'}</button>}</div></>)}
    {current&&<div className="mt-3" data-irp-question={current.kind}><QuestionHeader source={current.source} index={questions.indexOf(current)+1} total={questions.length}/>{current.kind==='funding'&&card(<>
      <p className="text-sm font-semibold">이 계좌의 현재 잔액은 어떤 돈으로 이루어져 있나요?</p><p className="text-xs text-gray-400">세금은 계좌 이름이 아니라 돈의 출처에 따라 달라집니다. 금융회사 앱의 ‘납입원금/과세제외/이연퇴직소득’ 내역을 확인하세요.</p>
      <div className="grid gap-2 sm:grid-cols-2"><Choice title="퇴직금 원금만" note="퇴직금이 들어왔고 운용수익이 전혀 없음을 확인" onClick={()=>patch(current.source.id,{fundingKind:'retirement'})}/><Choice title="개인납입금·운용수익만" note="세액공제 받은 개인 납입금과 계좌 수익" onClick={()=>patch(current.source.id,{fundingKind:'personal'})}/><Choice title="세액공제 안 받은 원금만" note="과세제외 금액만 있고 다른 재원이 없음" onClick={()=>patch(current.source.id,{fundingKind:'exempt'})}/><Choice title="여러 종류가 섞임" note="보통 운용 중인 퇴직·개인 IRP는 여기에 해당" onClick={()=>patch(current.source.id,{fundingKind:'mixed'})}/></div>
      <Unknown onSkip={skip}>금융회사 앱에서 구분이 안 보이면 고객센터에 “현재 연금계좌의 이연퇴직소득, 과세제외 금액, 세액공제 받은 개인부담금과 운용수익 구분”을 요청하세요.</Unknown></>)}
      {current.kind==='retirementPrincipal'&&card(<AmountQuestion source={current.source} title="현재 잔액 중 퇴직금 원금은 얼마인가요?" description="앞으로 들어올 퇴직금은 제외합니다. 현재 계좌에 이미 들어 있는 이연퇴직소득 원금만 입력하세요." evidence="금융회사 연금계좌 내역의 ‘이연퇴직소득’ 또는 ‘퇴직급여 입금액’을 확인하세요. 운용수익은 이 금액에 더하지 않습니다." value={draftValue(current.key)} onValue={v=>set(current.key,v)} onApply={n=>patch(current.source.id,{retirementPrincipal:n})} onSkip={skip}/>) }
      {current.kind==='exemptPrincipal'&&card(<AmountQuestion source={current.source} title="현재 잔액 중 세액공제를 받지 않은 원금은 얼마인가요?" description="연말정산에서 세액공제를 받지 않은 개인 납입 원금입니다. 해당 금액이 없음을 확인했다면 0원을 입력합니다." evidence="금융회사 앱의 ‘과세제외 금액’ 또는 연금납입확인서를 확인하세요. 세액공제를 받은 개인납입금은 여기에 넣지 않습니다." value={draftValue(current.key)} onValue={v=>set(current.key,v)} onApply={n=>patch(current.source.id,{exemptPrincipal:n})} onSkip={skip}/>) }
      {current.kind==='splitInvalid'&&card(<SplitCorrection source={current.source} settings={value.sources?.[current.source.id]??{}} onApply={(retirementPrincipal,exemptPrincipal)=>patch(current.source.id,{retirementPrincipal,exemptPrincipal})} onSkip={skip}/>) }
      {current.kind==='retirementTaxRate'&&card(<RateQuestion source={current.source} direct={draftValue(current.key+':direct')} tax={draftValue(current.key+':tax')} income={draftValue(current.key+':income')} setDirect={v=>set(current.key+':direct',v)} setTax={v=>set(current.key+':tax',v)} setIncome={v=>set(current.key+':income',v)} onApply={n=>patch(current.source.id,{retirementTaxRate:n})} onSkip={skip}/>) }
      {current.kind==='firstReceiptYear'&&card(<FirstYearQuestion source={current.source} value={draftValue(current.key,String(current.source.expectedStartYear??plan.startYear))} onValue={v=>set(current.key,v)} onApply={n=>patch(current.source.id,{firstReceiptYear:n})} onSkip={skip}/>) }
      {current.kind==='lifetime'&&card(<><p className="text-sm font-semibold">이 계좌는 중도해지가 불가능한 종신연금 계약인가요?</p><p className="text-xs text-gray-400">일반 IRP에서 기간을 정해 나눠 받는 경우는 ‘아니요’입니다. 사망할 때까지 지급되고 중도해지가 불가능한 보험형 종신연금만 ‘예’입니다.</p><div className="grid gap-2 sm:grid-cols-2"><Choice title="예 · 종신계약" note="중도해지 불가와 종신 지급을 모두 확인" onClick={()=>patch(current.source.id,{lifetime:true})}/><Choice title="아니요 · 일반 IRP/기간형" note="일정 기간 분할 수령하거나 해지 가능한 계좌" onClick={()=>patch(current.source.id,{lifetime:false})}/></div><Unknown onSkip={skip}>가입한 금융회사 상품 상세에서 ‘종신형’과 ‘중도해지 불가’가 모두 명시됐는지 확인하세요.</Unknown></>)}
    </div>}
    {dirty&&current&&<p className="mt-3 text-xs text-amber-200">답변은 아직 화면에만 반영됐습니다. 문답을 마친 뒤 ‘답변을 실제 데이터에 저장’을 눌러야 다음 접속과 백업에 포함됩니다.</p>}
  </section>
}

function QuestionHeader({source,index,total}:{source:PensionSource;index:number;total:number}){return <div className="flex flex-wrap justify-between gap-2 text-xs"><b className="break-words text-blue-200">{source.name} · {source.owner==='wife'?'아내':'남편'}</b><span className="text-gray-400">현재 잔액 {won(source.principal)} · {index}/{total}</span></div>}
function Choice({title,note,onClick}:{title:string;note:string;onClick:()=>void}){return <button type="button" className={button} onClick={onClick}><b className="block text-gray-100">{title}</b><span className="mt-1 block text-gray-400">{note}</span></button>}
function Unknown({children,onSkip}:{children:ReactNode;onSkip:()=>void}){return <details className="rounded border border-gray-700 p-2 text-xs text-gray-400"><summary className="cursor-pointer text-amber-200">잘 모르겠어요 · 무엇을 확인하나요?</summary><p className="mt-2">{children}</p><button type="button" className="mt-2 text-blue-300 underline" onClick={onSkip}>값을 추측하지 않고 이번에는 건너뛰기</button></details>}
function AmountQuestion({source,title,description,evidence,value,onValue,onApply,onSkip}:{source:PensionSource;title:string;description:string;evidence:string;value:string;onValue:(v:string)=>void;onApply:(n:number)=>void;onSkip:()=>void}){const n=Number(value),valid=value.trim()!==''&&Number.isFinite(n)&&n>=0&&n<=source.principal;return <><p className="text-sm font-semibold">{title}</p><p className="text-xs text-gray-400">{description}</p><label className="text-xs">금액 (원)<input aria-label={`${source.name} ${title}`} className={input} type="number" min="0" max={source.principal} value={value} onChange={e=>onValue(e.target.value)}/></label>{value&& !valid&&<p role="alert" className="text-xs text-red-300">0원 이상, 현재 잔액 {won(source.principal)} 이하로 입력하세요.</p>}<div className="flex gap-2"><button type="button" className="rounded bg-blue-600 px-3 py-2 text-xs disabled:opacity-50" disabled={!valid} onClick={()=>onApply(n)}>이 답변 적용</button><button type="button" className={button} onClick={()=>onApply(0)}>확인 결과 해당 없음 · 0원</button></div><Unknown onSkip={onSkip}>{evidence}</Unknown></>}
function SplitCorrection({source,settings,onApply,onSkip}:{source:PensionSource;settings:PensionSourceTaxSettings;onApply:(r:number,e:number)=>void;onSkip:()=>void}){const [r,setR]=useState(String(settings.retirementPrincipal??'')),[e,setE]=useState(String(settings.exemptPrincipal??''));const rn=Number(r),en=Number(e),valid=r!==''&&e!==''&&rn>=0&&en>=0&&rn+en<=source.principal;return <><p className="text-sm font-semibold">입력한 원금 합계가 현재 잔액보다 큽니다.</p><p className="text-xs text-gray-400">두 원금의 합계는 현재 잔액 {won(source.principal)} 이하여야 합니다. 남는 금액은 세액공제 받은 개인납입금·운용수익으로 계산합니다.</p><div className="grid gap-2 sm:grid-cols-2"><label className="text-xs">퇴직금 원금<input className={input} type="number" min="0" value={r} onChange={x=>setR(x.target.value)}/></label><label className="text-xs">과세제외 원금<input className={input} type="number" min="0" value={e} onChange={x=>setE(x.target.value)}/></label></div><button type="button" className="rounded bg-blue-600 px-3 py-2 text-xs disabled:opacity-50" disabled={!valid} onClick={()=>onApply(rn,en)}>수정값 적용</button><Unknown onSkip={onSkip}>금융회사에서 두 항목을 각각 확인한 뒤 합계가 현재 평가액을 넘지 않는지 확인하세요.</Unknown></>}
function RateQuestion({source,direct,tax,income,setDirect,setTax,setIncome,onApply,onSkip}:{source:PensionSource;direct:string;tax:string;income:string;setDirect:(v:string)=>void;setTax:(v:string)=>void;setIncome:(v:string)=>void;onApply:(n:number)=>void;onSkip:()=>void}){const d=Number(direct),t=Number(tax),i=Number(income),directOk=direct!==''&&d>=0&&d<=100,calcOk=tax!==''&&income!==''&&t>=0&&i>0&&t<=i,calculated=calcOk?t/i*100:null;return <><p className="text-sm font-semibold">현재 들어 있는 퇴직금의 이연퇴직소득세율은 얼마인가요?</p><p className="text-xs text-gray-400">예상 세율을 임의로 넣지 않습니다. 퇴직소득 원천징수영수증 또는 금융회사 이연 내역의 국세 금액을 사용합니다. 지방소득세는 넣지 않습니다.</p><label className="text-xs">세율을 아는 경우 (%)<input aria-label={`${source.name} 문답 이연퇴직소득세율`} className={input} type="number" min="0" max="100" step="any" value={direct} onChange={e=>setDirect(e.target.value)}/></label><button type="button" className="rounded bg-blue-600 px-3 py-2 text-xs disabled:opacity-50" disabled={!directOk} onClick={()=>onApply(d)}>세율 적용</button><details className="rounded border border-gray-700 p-2"><summary className="cursor-pointer text-xs text-blue-200">세율 대신 서류의 두 금액으로 계산하기</summary><p className="my-2 text-xs text-gray-400">이연퇴직소득세율 = 이연된 퇴직소득세(국세) ÷ 이연퇴직소득 × 100</p><div className="grid gap-2 sm:grid-cols-2"><label className="text-xs">이연퇴직소득세 · 국세 (원)<input aria-label={`${source.name} 문답 이연퇴직소득세 국세`} className={input} type="number" min="0" value={tax} onChange={e=>setTax(e.target.value)}/></label><label className="text-xs">이연퇴직소득 (원)<input aria-label={`${source.name} 문답 이연퇴직소득`} className={input} type="number" min="1" value={income} onChange={e=>setIncome(e.target.value)}/></label></div>{calculated!=null&&<p className="mt-2 text-xs text-emerald-300">계산 결과 {calculated.toFixed(4)}%</p>}<button type="button" className="mt-2 rounded bg-blue-600 px-3 py-2 text-xs disabled:opacity-50" disabled={calculated==null} onClick={()=>onApply(calculated!)}>계산한 세율 적용</button></details><Unknown onSkip={onSkip}>퇴직소득 원천징수영수증의 이연퇴직소득세(국세)와 이연퇴직소득을 확인하거나 금융회사에 문의하세요. 새로 받을 퇴직금의 세율은 목돈 항목에서 별도로 입력합니다.</Unknown></>}
function FirstYearQuestion({source,value,onValue,onApply,onSkip}:{source:PensionSource;value:string;onValue:(v:string)=>void;onApply:(n:number)=>void;onSkip:()=>void}){const n=Number(value),valid=Number.isInteger(n)&&n>=1900&&n<=2200;return <><p className="text-sm font-semibold">이 퇴직금 재원에서 처음 연금을 받는 연도는 언제인가요?</p><p className="text-xs text-gray-400">이미 받았다면 실제 첫 지급연도, 아직 받기 전이면 계획된 첫 지급연도를 입력합니다. 세법상 수령연차 계산에 사용됩니다.</p><label className="text-xs">첫 수령연도<input aria-label={`${source.name} 문답 첫 수령연도`} className={input} type="number" min="1900" max="2200" step="1" value={value} onChange={e=>onValue(e.target.value)}/></label><button type="button" className="rounded bg-blue-600 px-3 py-2 text-xs disabled:opacity-50" disabled={!valid} onClick={()=>onApply(n)}>이 연도 적용</button><Unknown onSkip={onSkip}>금융회사 지급내역의 최초 연금 지급일을 확인하세요. 아직 개시 전이면 등록된 지급개시 예정연도 {source.expectedStartYear??'미입력'}를 확인한 뒤 사용하세요.</Unknown></>}
